// Generated by Xata Codegen 0.22.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "users",
    columns: [
      { name: "displayName", type: "string", unique: true },
      { name: "name", type: "string" },
      { name: "email", type: "email", unique: true },
      { name: "password", type: "string" },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      {
        name: "updatedAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "description", type: "string" },
      { name: "location", type: "string" },
      { name: "pinnedTweet", type: "link", link: { table: "tweets" } },
    ],
  },
  {
    name: "tweets",
    columns: [
      { name: "text", type: "string", notNull: true, defaultValue: '""' },
      { name: "user", type: "link", link: { table: "users" } },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "likeCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "retweetOf", type: "link", link: { table: "tweets" } },
      { name: "retweetCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "quoteOf", type: "link", link: { table: "tweets" } },
      { name: "quoteCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "replyOf", type: "link", link: { table: "tweets" } },
      { name: "replyCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "hashtags", type: "multiple" },
    ],
  },
  {
    name: "bookmarks",
    columns: [
      { name: "tweet", type: "link", link: { table: "tweets" } },
      { name: "user", type: "link", link: { table: "users" } },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
    ],
  },
  {
    name: "likes",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "tweet", type: "link", link: { table: "tweets" } },
      { name: "likedAt", type: "datetime", notNull: true, defaultValue: "now" },
    ],
  },
  {
    name: "notifications",
    columns: [
      { name: "from", type: "link", link: { table: "users" } },
      { name: "to", type: "link", link: { table: "users" } },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "tweet", type: "link", link: { table: "tweets" } },
      { name: "type", type: "string" },
      { name: "reply", type: "link", link: { table: "tweets" } },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Tweets = InferredTypes["tweets"];
export type TweetsRecord = Tweets & XataRecord;

export type Bookmarks = InferredTypes["bookmarks"];
export type BookmarksRecord = Bookmarks & XataRecord;

export type Likes = InferredTypes["likes"];
export type LikesRecord = Likes & XataRecord;

export type Notifications = InferredTypes["notifications"];
export type NotificationsRecord = Notifications & XataRecord;

export type DatabaseSchema = {
  users: UsersRecord;
  tweets: TweetsRecord;
  bookmarks: BookmarksRecord;
  likes: LikesRecord;
  notifications: NotificationsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://primera-vk1k74.us-east-1.xata.sh/db/twitter",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
