// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "user",
    columns: [
      { name: "displayName", type: "string", unique: true },
      { name: "name", type: "string" },
      { name: "email", type: "email", unique: true },
      { name: "password", type: "string" },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      {
        name: "updatedAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "description", type: "string" },
      { name: "location", type: "string" },
      { name: "pinnedTweet", type: "link", link: { table: "tweet" } },
      { name: "followerCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "followingCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "tweetCount", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
  {
    name: "tweet",
    columns: [
      { name: "text", type: "string", notNull: true, defaultValue: '""' },
      { name: "user", type: "link", link: { table: "user" } },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "likeCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "retweetOf", type: "link", link: { table: "tweet" } },
      { name: "retweetCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "quoteOf", type: "link", link: { table: "tweet" } },
      { name: "quoteCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "replyOf", type: "link", link: { table: "tweet" } },
      { name: "replyCount", type: "int", notNull: true, defaultValue: "0" },
      { name: "bookmarkCount", type: "int", notNull: true, defaultValue: "0" },
      {
        name: "entities",
        type: "object",
        columns: [{ name: "hashtags", type: "multiple" }],
      },
    ],
  },
  {
    name: "bookmark",
    columns: [
      { name: "tweet", type: "link", link: { table: "tweet" } },
      { name: "user", type: "link", link: { table: "user" } },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
    ],
  },
  {
    name: "like",
    columns: [
      { name: "user", type: "link", link: { table: "user" } },
      { name: "tweet", type: "link", link: { table: "tweet" } },
      { name: "likedAt", type: "datetime", notNull: true, defaultValue: "now" },
    ],
  },
  {
    name: "notification",
    columns: [
      { name: "from", type: "link", link: { table: "user" } },
      { name: "to", type: "link", link: { table: "user" } },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "tweet", type: "link", link: { table: "tweet" } },
      { name: "type", type: "string" },
      { name: "reply", type: "link", link: { table: "tweet" } },
    ],
  },
  {
    name: "folder",
    columns: [
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "user", type: "link", link: { table: "user" } },
    ],
  },
  {
    name: "follow",
    columns: [
      { name: "follower", type: "link", link: { table: "user" } },
      { name: "followed", type: "link", link: { table: "user" } },
      {
        name: "followedAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
    ],
  },
  {
    name: "feed",
    columns: [
      { name: "user", type: "link", link: { table: "user" } },
      {
        name: "updatedAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
    ],
  },
  {
    name: "feedTweet",
    columns: [
      { name: "tweet", type: "link", link: { table: "tweet" } },
      { name: "feed", type: "link", link: { table: "feed" } },
    ],
  },
  {
    name: "chat",
    columns: [
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "createdBy", type: "link", link: { table: "user" } },
      { name: "recipient", type: "link", link: { table: "user" } },
      { name: "participants", type: "multiple" },
      { name: "lastMessage", type: "link", link: { table: "message" } },
      { name: "draft", type: "bool", notNull: true, defaultValue: "true" },
    ],
  },
  {
    name: "message",
    columns: [
      {
        name: "createdAt",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      { name: "user", type: "link", link: { table: "user" } },
      { name: "chat", type: "link", link: { table: "chat" } },
      { name: "text", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type User = InferredTypes["user"];
export type UserRecord = User & XataRecord;

export type Tweet = InferredTypes["tweet"];
export type TweetRecord = Tweet & XataRecord;

export type Bookmark = InferredTypes["bookmark"];
export type BookmarkRecord = Bookmark & XataRecord;

export type Like = InferredTypes["like"];
export type LikeRecord = Like & XataRecord;

export type Notification = InferredTypes["notification"];
export type NotificationRecord = Notification & XataRecord;

export type Folder = InferredTypes["folder"];
export type FolderRecord = Folder & XataRecord;

export type Follow = InferredTypes["follow"];
export type FollowRecord = Follow & XataRecord;

export type Feed = InferredTypes["feed"];
export type FeedRecord = Feed & XataRecord;

export type FeedTweet = InferredTypes["feedTweet"];
export type FeedTweetRecord = FeedTweet & XataRecord;

export type Chat = InferredTypes["chat"];
export type ChatRecord = Chat & XataRecord;

export type Message = InferredTypes["message"];
export type MessageRecord = Message & XataRecord;

export type DatabaseSchema = {
  user: UserRecord;
  tweet: TweetRecord;
  bookmark: BookmarkRecord;
  like: LikeRecord;
  notification: NotificationRecord;
  folder: FolderRecord;
  follow: FollowRecord;
  feed: FeedRecord;
  feedTweet: FeedTweetRecord;
  chat: ChatRecord;
  message: MessageRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://primera-vk1k74.us-east-1.xata.sh/db/twitter",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
